// This file is automatically generated by qtc from "basepage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
package templates

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
type Page interface {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	Title() string
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	StreamTitle(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	WriteTitle(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	Head() string
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	StreamHead(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	WriteHead(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	Header() string
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	StreamHeader(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	WriteHeader(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	Body() string
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	StreamBody(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
	WriteBody(qq422016 qtio422016.Writer)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:1
}

// PrintPage prints Page p

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:11
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:11
	qw422016.N().S(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>`)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:16
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:16
	qw422016.N().S(`</title><link rel="stylesheet" type="text/css" href="/css/main.css">`)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:18
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:18
	qw422016.N().S(`<base href="/"></head><body><header>`)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:23
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:23
	qw422016.N().S(`</header><hr>`)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:26
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:26
	qw422016.N().S(`</body></html>`)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	StreamPageTemplate(qw422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
func PageTemplate(p Page) string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	WritePageTemplate(qb422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:29
}

// Base page implementation. Other pages may inherit from it if they need overriding only certain Page methods

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:32
type BasePage struct{}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
qw422016.N().S(`Spiders Welcome`) }

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
func (p *BasePage) Title() string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:33
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
func (p *BasePage) StreamHead(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
func (p *BasePage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
func (p *BasePage) Head() string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:34
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
func (p *BasePage) StreamHeader(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
qw422016.N().S(`Default Header`) }

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
func (p *BasePage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
func (p *BasePage) Header() string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:35
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
qw422016.N().S(`Default Body`) }

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
func (p *BasePage) Body() string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:36
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:38
func StreamStrFallback(qw422016 *qt422016.Writer, strings ...string) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:40
	firstStr := ""
	for _, str := range strings {
		if str != "" {
			firstStr = str
			break
		}
	}

	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:48
	qw422016.N().S(firstStr)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
func WriteStrFallback(qq422016 qtio422016.Writer, strings ...string) {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	StreamStrFallback(qw422016, strings...)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
func StrFallback(strings ...string) string {
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	WriteStrFallback(qb422016, strings...)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:49
}

//line src\github.com\t3chguy\matrix-static\templates\basepage.qtpl:52
func Str(a interface{}) string {
	str, _ := a.(string)
	return str
}
