// This file is automatically generated by qtc from "pagination-common.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Simple pagination helpers, empty string means no such pagination possible
// Makes a lot of assumptions specific to all but one of the paginatable pages.
// AllPage = page 0
// There is always a PrevPage if curPage > 1
// Pages are ints and can be +/- 1 to get siblings

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:6
package templates

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:6
type Paginator interface {
	CurPage() int
	HasNextPage() bool
	BaseUrl() string
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:12
func StreamPaginatorCurPage(qw422016 *qt422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:12
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:13
	curPage := p.CurPage()

	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:13
	qw422016.N().S(`
    <div>
        `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:15
	if curPage > 0 {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:15
		qw422016.N().S(`
            Page `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:16
		qw422016.N().S(` `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:16
		qw422016.N().D(curPage)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:16
		qw422016.N().S(`
        `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:17
	} else {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:17
		qw422016.N().S(`
            All Pages
        `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:19
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:19
	qw422016.N().S(`
    </div>
`)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
func WritePaginatorCurPage(qq422016 qtio422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	StreamPaginatorCurPage(qw422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
func PaginatorCurPage(p Paginator) string {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	WritePaginatorCurPage(qb422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:23
func StreamPaginatorFooter(qw422016 *qt422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:23
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:25
	curPage := p.CurPage()
	baseUrl := p.BaseUrl()

	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:27
	qw422016.N().S(`

    <footer>
        <span style="float: left;">
            <span>
                `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:32
	if curPage > 1 {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:32
		qw422016.N().S(`
                    <a href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:33
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:33
		qw422016.N().S(`?page=`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:33
		qw422016.N().D(curPage - 1)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:33
		qw422016.N().S(`">Previous Page</a>
                `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:34
	} else if curPage == 1 {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:34
		qw422016.N().S(`
                    <a href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:35
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:35
		qw422016.N().S(`?page=0">See All</a>
                `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:36
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:36
	qw422016.N().S(`
            </span>
            `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:38
	qw422016.N().S(` `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:38
	qw422016.N().S(`
            <span>
                `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:40
	if curPage == 0 {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:40
		qw422016.N().S(`
                    <a href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:41
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:41
		qw422016.N().S(`?page=1">First Page</a>
                `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:42
	} else if p.HasNextPage() {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:42
		qw422016.N().S(`
                    <a href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:43
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:43
		qw422016.N().S(`?page=`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:43
		qw422016.N().D(curPage + 1)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:43
		qw422016.N().S(`">Next Page</a>
                `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:44
	} else {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:44
		qw422016.N().S(`
                    <a href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:45
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:45
		qw422016.N().S(`?page=0">See All</a>
                `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:46
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:46
	qw422016.N().S(`
            </span>
        </span>
        `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:49
	if baseUrl != "./" {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:49
		qw422016.N().S(`
            <span style="float: right;">
                <a href="./">Back to Room List</a>
            </span>
        `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:53
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:53
	qw422016.N().S(`
        <span style="clear: both;"></span>
    </footer>
`)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
func WritePaginatorFooter(qq422016 qtio422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	StreamPaginatorFooter(qw422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
func PaginatorFooter(p Paginator) string {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	WritePaginatorFooter(qb422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:56
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:58
func StreamPaginatorHeadLinks(qw422016 *qt422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:58
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:60
	curPage := p.CurPage()
	baseUrl := p.BaseUrl()

	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:62
	qw422016.N().S(`

    <link rel="canonical" href="`)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:64
	qw422016.E().S(baseUrl)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:64
	qw422016.N().S(`?page=0">

    `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:66
	if curPage > 1 {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:66
		qw422016.N().S(`
        <link rel="prev" href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:67
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:67
		qw422016.N().S(`?page=`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:67
		qw422016.N().D(curPage - 1)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:67
		qw422016.N().S(`">
    `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:68
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:68
	qw422016.N().S(`

    `)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:70
	if p.HasNextPage() {
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:70
		qw422016.N().S(`
        <link rel="next" href="`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:71
		qw422016.E().S(baseUrl)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:71
		qw422016.N().S(`?page=`)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:71
		qw422016.N().D(curPage + 1)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:71
		qw422016.N().S(`">
    `)
		//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:72
	}
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:72
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
func WritePaginatorHeadLinks(qq422016 qtio422016.Writer, p Paginator) {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	StreamPaginatorHeadLinks(qw422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
}

//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
func PaginatorHeadLinks(p Paginator) string {
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	WritePaginatorHeadLinks(qb422016, p)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\pagination-common.qtpl:73
}
