// This file is automatically generated by qtc from "room-error.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:1
package templates

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:1
import "github.com/t3chguy/matrix-static/mxclient"

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:5
type RoomErrorPage struct {
	RoomInfo mxclient.RoomInfo
	Error    string
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:12
func (p *RoomErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:12
	qw422016.N().S(`
    Public Room ERROR - `)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:13
	qw422016.E().S(p.RoomInfo.Name)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:13
	qw422016.N().S(` - Riot Static
`)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
func (p *RoomErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
func (p *RoomErrorPage) Title() string {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:14
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:16
func (p *RoomErrorPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:16
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
func (p *RoomErrorPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
func (p *RoomErrorPage) Head() string {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:17
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:19
func (p *RoomErrorPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:19
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:20
	StreamPrintRoomHeader(qw422016, p.RoomInfo)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:20
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
func (p *RoomErrorPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
func (p *RoomErrorPage) Header() string {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:21
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:24
func (p *RoomErrorPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:24
	qw422016.N().S(`<div class="errMsg"><h1>`)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:27
	qw422016.E().S(p.Error)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:27
	qw422016.N().S(`</h1></div><a href="./">Back to Room List</a>`)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
func (p *RoomErrorPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
}

//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
func (p *RoomErrorPage) Body() string {
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
	return qs422016
//line src\github.com\t3chguy\matrix-static\templates\room-error.qtpl:32
}
