// This file is automatically generated by qtc from "basepage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
package templates

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
type Page interface {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	Title() string
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	StreamTitle(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	WriteTitle(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	Head() string
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	StreamHead(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	WriteHead(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	Header() string
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	StreamHeader(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	WriteHeader(qq422016 qtio422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	Body() string
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	StreamBody(qw422016 *qt422016.Writer)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
	WriteBody(qq422016 qtio422016.Writer)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:1
}

// PrintPage prints Page p

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:11
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:11
	qw422016.N().S(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>`)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:16
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:16
	qw422016.N().S(`</title><style>/*tr {*//*height: 64px;*//*}*/img.userAvatar {height: 20px;}* {font-family: 'Open Sans',Arial,Helvetica,Sans-Serif;}img.roomLogo {height: 64px;}table#roomHeader {width: 100%;}table#roomList img {height: 60px;}td.rightAlign {text-align: right;min-width: 120px;}div.paginate {text-align: center;}/*td.maxWidth {*//*width: 100%;*//*}*/h2 {margin: 0;}span.redacted {color: red;}</style>`)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:53
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:53
	qw422016.N().S(`<base href="/"></head><body><header>`)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:58
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:58
	qw422016.N().S(`</header><hr>`)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:61
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:61
	qw422016.N().S(`</body></html>`)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	StreamPageTemplate(qw422016, p)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
func PageTemplate(p Page) string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	WritePageTemplate(qb422016, p)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:64
}

// Base page implementation. Other pages may inherit from it if they need overriding only certain Page methods

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:67
type BasePage struct{}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
qw422016.N().S(`Spiders Welcome`) }

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
func (p *BasePage) Title() string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:68
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
func (p *BasePage) StreamHead(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
func (p *BasePage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
func (p *BasePage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
func (p *BasePage) StreamHeader(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
qw422016.N().S(`Default Header`) }

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
func (p *BasePage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
func (p *BasePage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:70
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
qw422016.N().S(`Default Body`) }

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
func (p *BasePage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:71
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:73
func StreamStrFallback(qw422016 *qt422016.Writer, strings ...string) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:75
	firstStr := ""
	for _, str := range strings {
		if str != "" {
			firstStr = str
			break
		}
	}

	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:83
	qw422016.N().S(firstStr)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
func WriteStrFallback(qq422016 qtio422016.Writer, strings ...string) {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	StreamStrFallback(qw422016, strings...)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
func StrFallback(strings ...string) string {
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	WriteStrFallback(qb422016, strings...)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:84
}

//line src\github.com\t3chguy\riot-static\templates\basepage.qtpl:87
func Str(a interface{}) string {
	str, _ := a.(string)
	return str
}
