// This file is automatically generated by qtc from "room-chat.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:1
package templates

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:1
import "time"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:2
import "github.com/matrix-org/gomatrix"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:3
import "github.com/t3chguy/riot-static/mxclient"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:4
import "github.com/t3chguy/riot-static/sanitizer"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
func streamprintTimestamp(qw422016 *qt422016.Writer, unixTime int) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:9
	qw422016.E().S(time.Unix(0, int64(unixTime)*int64(time.Millisecond)).Format("2 Jan 2006 15:04:05"))
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:9
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
func writeprintTimestamp(qq422016 qtio422016.Writer, unixTime int) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	streamprintTimestamp(qw422016, unixTime)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
func printTimestamp(unixTime int) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	writeprintTimestamp(qb422016, unixTime)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:15
type MemberEventContent struct {
	Membership  string
	AvatarURL   mxclient.MXCURL
	DisplayName string
}

func convertContentToMEC(content map[string]interface{}, homeserverBaseUrl string) (mec MemberEventContent) {
	if membership, ok := content["membership"].(string); ok {
		mec.Membership = membership
	}
	if avatarUrl, ok := content["avatar_url"].(string); ok {
		mec.AvatarURL = *mxclient.NewMXCURL(avatarUrl, homeserverBaseUrl)
	}
	if displayName, ok := content["displayname"].(string); ok {
		mec.DisplayName = displayName
	}

	return
}

func getMemberEventContent(ev gomatrix.Event, homeserverBaseUrl string) MemberEventContent {
	return convertContentToMEC(ev.Content, homeserverBaseUrl)
}

func getMemberEventPrevContent(ev gomatrix.Event, homeserverBaseUrl string) MemberEventContent {
	return convertContentToMEC(ev.PrevContent, homeserverBaseUrl)
}

type RoomChatPage struct {
	RoomInfo          mxclient.RoomInfo
	MemberMap         map[string]*mxclient.MemberInfo
	Events            []gomatrix.Event
	PageSize          int
	ReachedRoomCreate bool
	CurrentOffset     int
	Anchor            string

	Sanitizer         *sanitizer.Sanitizer
	HomeserverBaseURL string
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:59
func (p *RoomChatPage) streamtextForMRoomMemberEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:59
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:61
	content := getMemberEventContent(ev, p.HomeserverBaseURL)
	prevContent := getMemberEventPrevContent(ev, p.HomeserverBaseURL)

	sender := ev.Sender
	target := *ev.StateKey
	senderPretty := p.MemberMap[sender].GetName()
	targetPretty := p.MemberMap[target].GetName()

	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:68
	qw422016.N().S(`

    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:70
	switch content.Membership {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:71
	case "invite":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:71
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:72
		qw422016.E().S(senderPretty)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:72
		qw422016.N().S(` invited `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:72
		qw422016.E().S(targetPretty)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:72
		qw422016.N().S(`.
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:73
	case "ban":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:73
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:75
		var reasonString string
		if reason, ok := ev.Content["reason"].(string); ok {
			reasonString = " (" + reason + ")"
		}

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:79
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		qw422016.E().S(senderPretty)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		qw422016.N().S(` banned `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		qw422016.E().S(targetPretty)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		qw422016.E().S(reasonString)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		qw422016.N().S(`.
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:81
	case "join":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:81
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
		if ev.PrevContent != nil && prevContent.Membership == "join" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:83
			if prevContent.DisplayName == "" && content.DisplayName != "" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:83
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.N().S(` set their display name to `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.E().S(content.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:85
			} else if prevContent.DisplayName != "" && content.DisplayName == "" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:85
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.N().S(` removed their display name `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.E().S(prevContent.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:87
			} else if prevContent.DisplayName != content.DisplayName {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:87
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.N().S(` changed their display name from `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.E().S(prevContent.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.N().S(` to `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.E().S(content.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:89
			} else if !prevContent.AvatarURL.IsValid() && content.AvatarURL.IsValid() {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:89
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:90
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:90
				qw422016.N().S(` set a profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:91
			} else if prevContent.AvatarURL.IsValid() && !content.AvatarURL.IsValid() {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:91
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:92
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:92
				qw422016.N().S(` removed their profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:93
			} else if prevContent.AvatarURL != content.AvatarURL {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:93
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:94
				qw422016.E().S(senderPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:94
				qw422016.N().S(` changed their profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:95
			}
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:95
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:96
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:96
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:97
			qw422016.E().S(targetPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:97
			qw422016.N().S(` joined the room.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:98
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:98
		qw422016.N().S(`
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:99
	case "leave":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:99
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:100
		if sender == target {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:100
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:101
			if prevContent.Membership == "invite" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:101
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:102
				qw422016.E().S(targetPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:102
				qw422016.N().S(` rejected invite.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:103
			} else {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:103
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:104
				qw422016.E().S(targetPretty)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:104
				qw422016.N().S(` left the room.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			}
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:106
		} else if prevContent.Membership == "ban" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:106
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.E().S(senderPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.N().S(` unbanned `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.E().S(targetPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.N().S(`.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:108
		} else if prevContent.Membership == "leave" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:108
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.E().S(senderPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.N().S(` kicked `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.E().S(targetPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.N().S(`.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:110
		} else if prevContent.Membership == "invite" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:110
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			qw422016.E().S(senderPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			qw422016.N().S(` withdrew `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			qw422016.E().S(targetPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			qw422016.N().S(`'s invite.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:112
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:112
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:113
			qw422016.E().S(targetPretty)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:113
			qw422016.N().S(` left the room.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
		qw422016.N().S(`
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:115
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:115
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
func (p *RoomChatPage) writetextForMRoomMemberEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	p.streamtextForMRoomMemberEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
func (p *RoomChatPage) textForMRoomMemberEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	p.writetextForMRoomMemberEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:118
func (p *RoomChatPage) streamtextForMRoomMessageEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:118
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:119
	switch ev.Content["msgtype"] {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:120
	case "m.image":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:120
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:122
		url := ev.Content["url"].(string)

		if thumbUrl, ok := ev.Content["thumbnail_url"].(string); ok {
			url = thumbUrl
		}

		mxc := mxclient.NewMXCURL(url, p.HomeserverBaseURL)

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:129
		qw422016.N().S(`
            <a href="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:130
		qw422016.E().S(mxc.ToURL())
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:130
		qw422016.N().S(`" rel="noopener">
                <img src="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:131
		qw422016.E().S(mxc.ToThumbURL(360, 360, "scale"))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:131
		qw422016.N().S(`" />
                <br>
                <sup>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:133
		qw422016.E().S(Str(ev.Content["body"]))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:133
		qw422016.N().S(`</sup>
            </a>
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:135
	case "m.file":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:135
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:136
		mxc := mxclient.NewMXCURL(Str(ev.Content["url"]), p.HomeserverBaseURL)

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:136
		qw422016.N().S(`
            <a href="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:137
		qw422016.E().S(mxc.ToURL())
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:137
		qw422016.N().S(`" rel="noopener">
                `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:138
		if ev.Content["thumbnail_url"] != "" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:138
			qw422016.N().S(`
                    <img src="`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:139
			qw422016.E().S(mxc.ToThumbURL(360, 360, "scale"))
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:139
			qw422016.N().S(`" />
                    <br>
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:141
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:141
		qw422016.N().S(`
                <sup>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:142
		qw422016.E().S(Str(ev.Content["body"]))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:142
		qw422016.N().S(`</sup>
            </a>
            m.file
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:145
	case "m.location":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:145
		qw422016.N().S(`
            m.location Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:147
	case "m.video":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:147
		qw422016.N().S(`
            m.video Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:149
	case "m.audio":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:149
		qw422016.N().S(`
            m.audio Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:151
	default:
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:151
		qw422016.N().S(` `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:151
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:153
		var formattedOk bool
		var sanitizedFormattedBody, body string

		if ev.Content["format"] == "org.matrix.custom.html" {
			if formattedBodyStr, ok := ev.Content["formatted_body"].(string); ok {
				sanitizedFormattedBody, formattedOk = p.Sanitizer.Sanitize(formattedBodyStr)
			}
		}
		if !formattedOk {
			if bodyStr, ok := ev.Content["body"].(string); ok {
				body = bodyStr
			}
		}

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:166
		qw422016.N().S(`

            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:168
		if formattedOk {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:168
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:169
			qw422016.N().S(sanitizedFormattedBody)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:169
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:170
		} else if body != "" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:170
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:171
			qw422016.E().S(body)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:171
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:172
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:172
			qw422016.N().S(`
                <span class="redacted">Redacted or Malformed Event</span>
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
		qw422016.N().S(`
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:175
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:175
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
func (p *RoomChatPage) writetextForMRoomMessageEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	p.streamtextForMRoomMessageEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
func (p *RoomChatPage) textForMRoomMessageEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	p.writetextForMRoomMessageEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:179
func (p *RoomChatPage) streamprintEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:181
	memberInfo := p.MemberMap[ev.Sender]

	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:182
	qw422016.N().S(`<tr>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:185
	p.streamprintPermalinkColumn(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:186
	switch ev.Type {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
	case "m.room.message":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
		qw422016.N().S(`<td nowrap><a href="./room/`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.E().S(p.RoomInfo.RoomID)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.N().S(`/members/`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.E().S(ev.Sender)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.N().S(`">`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
		if memberInfo.AvatarURL.IsValid() {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
			qw422016.N().S(`<img class="avatar userAvatar" src="`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:192
			qw422016.E().S(memberInfo.AvatarURL.ToThumbURL(48, 48, "crop"))
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:192
			qw422016.N().S(`" />`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:193
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:193
			qw422016.N().S(`<img class="avatar userAvatar" src="./img/logo_missing.png" />`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:195
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:197
		if ev.Content["msgtype"] == "m.emote" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:197
			qw422016.N().S(`*`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:197
			qw422016.N().S(` `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:197
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:199
		qw422016.E().S(memberInfo.GetName())
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:199
		qw422016.N().S(`</a></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:202
		p.streamtextForMRoomMessageEvent(qw422016, ev)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:202
		qw422016.N().S(`</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:203
	case "m.room.member":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:203
		qw422016.N().S(`<td></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:205
		p.streamtextForMRoomMemberEvent(qw422016, ev)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:205
		qw422016.N().S(`</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:206
	default:
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:206
		qw422016.N().S(`Default Event Renderer. Room topic name etc need renderers.`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:208
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:208
	qw422016.N().S(`</tr>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
func (p *RoomChatPage) writeprintEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	p.streamprintEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
func (p *RoomChatPage) printEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	p.writeprintEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:212
func (p *RoomChatPage) streamprintPermalinkColumn(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:212
	qw422016.N().S(`<td class="timestamp" nowrap><a href="https://matrix.to/#/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	qw422016.E().S(p.RoomInfo.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	qw422016.N().S(`/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	qw422016.E().S(ev.ID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	qw422016.N().S(`">`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	streamprintTimestamp(qw422016, ev.Timestamp)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	qw422016.N().S(`</a></td>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
func (p *RoomChatPage) writeprintPermalinkColumn(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	p.streamprintPermalinkColumn(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
func (p *RoomChatPage) printPermalinkColumn(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	p.writeprintPermalinkColumn(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:216
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:220
func (p *RoomChatPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:220
	qw422016.N().S(`Public Room Timeline -`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:221
	qw422016.E().S(p.RoomInfo.Name)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:221
	qw422016.N().S(`- Riot Static`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
func (p *RoomChatPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
func (p *RoomChatPage) Title() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:222
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:224
func (p *RoomChatPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:225
	if !p.ReachedRoomCreate {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:225
		qw422016.N().S(`<link rel="next" href="?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
		qw422016.N().D(p.CurrentOffset + p.PageSize)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
		qw422016.N().S(`">`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:227
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:228
	if len(p.Events) > 0 {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:228
		qw422016.N().S(`<link rel="prev" href="?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
		qw422016.N().D(p.CurrentOffset - len(p.Events))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
		qw422016.N().S(`">`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:230
	}
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
func (p *RoomChatPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
func (p *RoomChatPage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:233
func (p *RoomChatPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:234
	StreamPrintRoomHeader(qw422016, p.RoomInfo)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
func (p *RoomChatPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
func (p *RoomChatPage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:237
func (p *RoomChatPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:237
	qw422016.N().S(`<div class="paginate">`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:239
	if p.ReachedRoomCreate {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:239
		qw422016.N().S(`<h4>You have reached the beginning of time (for this room).</h4>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:241
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:241
		qw422016.N().S(`<a href="./room/`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.E().S(p.RoomInfo.RoomID)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.N().S(`/?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.N().D(p.CurrentOffset + p.PageSize)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:242
		qw422016.N().S(`"><h4>Load older messages</h4></a>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:245
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:245
	qw422016.N().S(`</div><hr>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:249
	if len(p.Events) > 0 {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:249
		qw422016.N().S(`<table class="timeline"><thead><tr><th>Timestamp</th><th>&nbsp;</th><th>Message</th></tr></thead><tbody>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:259
		for _, event := range p.Events {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:260
			p.streamprintEvent(qw422016, event)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:261
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:261
		qw422016.N().S(`</tbody></table>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:264
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:264
		qw422016.N().S(`<h3>No Events</h3>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:266
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:266
	qw422016.N().S(`<hr><div class="paginate"><a href="./room/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.E().S(p.RoomInfo.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.N().S(`/?anchor=`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.E().S(p.Anchor)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.N().S(`&offset=`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.N().D(p.CurrentOffset - len(p.Events))
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
	qw422016.N().S(`"><h4>Show newer messages</h4></a></div><hr><a href="./">Back to Room List</a>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
func (p *RoomChatPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
func (p *RoomChatPage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:277
}
