// This file is automatically generated by qtc from "room-chat.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:1
package templates

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:1
import "time"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:2
import "github.com/matrix-org/gomatrix"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:3
import "github.com/t3chguy/riot-static/mxclient"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:4
import "github.com/t3chguy/riot-static/sanitizer"

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
func streamprintTimestamp(qw422016 *qt422016.Writer, unixTime int) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:8
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:9
	qw422016.E().S(time.Unix(0, int64(unixTime)*int64(time.Millisecond)).Format("2 Jan 2006 15:04:05"))
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:9
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
func writeprintTimestamp(qq422016 qtio422016.Writer, unixTime int) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	streamprintTimestamp(qw422016, unixTime)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
func printTimestamp(unixTime int) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	writeprintTimestamp(qb422016, unixTime)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:10
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:15
type MemberEventContent struct {
	Membership  string
	AvatarURL   mxclient.MXCURL
	DisplayName string
}

func convertContentToMEC(content map[string]interface{}, homeserverBaseUrl string) (mec MemberEventContent) {
	if membership, ok := content["membership"].(string); ok {
		mec.Membership = membership
	}
	if avatarUrl, ok := content["avatar_url"].(string); ok {
		mec.AvatarURL = *mxclient.NewMXCURL(avatarUrl, homeserverBaseUrl)
	}
	if displayName, ok := content["displayname"].(string); ok {
		mec.DisplayName = displayName
	}

	return
}

func getMemberEventContent(ev gomatrix.Event, homeserverBaseUrl string) MemberEventContent {
	return convertContentToMEC(ev.Content, homeserverBaseUrl)
}

func getMemberEventPrevContent(ev gomatrix.Event, homeserverBaseUrl string) MemberEventContent {
	return convertContentToMEC(ev.PrevContent, homeserverBaseUrl)
}

type RoomChatPage struct {
	RoomInfo          mxclient.RoomInfo
	MemberMap         map[string]mxclient.MemberInfo
	Events            []gomatrix.Event
	PageSize          int
	ReachedRoomCreate bool
	CurrentOffset     int
	Anchor            string

	Sanitizer         *sanitizer.Sanitizer
	HomeserverBaseURL string
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:59
func (p *RoomChatPage) streamtextForMRoomMemberEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:59
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:61
	content := getMemberEventContent(ev, p.HomeserverBaseURL)
	prevContent := getMemberEventPrevContent(ev, p.HomeserverBaseURL)

	sender := ev.Sender
	target := *ev.StateKey

	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:66
	qw422016.N().S(`

    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:68
	switch content.Membership {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:69
	case "invite":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:69
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:70
		p.streamprettyPrintMember(qw422016, sender)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:70
		qw422016.N().S(` invited `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:70
		p.streamprettyPrintMember(qw422016, target)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:70
		qw422016.N().S(`.
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:71
	case "ban":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:71
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:73
		var reasonString string
		if reason, ok := ev.Content["reason"].(string); ok {
			reasonString = " (" + reason + ")"
		}

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:77
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:78
		p.streamprettyPrintMember(qw422016, sender)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:78
		qw422016.N().S(` banned `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:78
		p.streamprettyPrintMember(qw422016, target)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:78
		qw422016.E().S(reasonString)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:78
		qw422016.N().S(`.
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:79
	case "join":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:79
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
		if ev.PrevContent != nil && prevContent.Membership == "join" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:80
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:81
			if prevContent.DisplayName == "" && content.DisplayName != "" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:81
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
				qw422016.N().S(` set their display name to `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
				qw422016.E().S(content.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:82
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:83
			} else if prevContent.DisplayName != "" && content.DisplayName == "" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:83
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.N().S(` removed their display name `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.E().S(prevContent.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:84
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:85
			} else if prevContent.DisplayName != content.DisplayName {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:85
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.N().S(` changed their display name from `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.E().S(prevContent.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.N().S(` to `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.E().S(content.DisplayName)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:86
				qw422016.N().S(`.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:87
			} else if !prevContent.AvatarURL.IsValid() && content.AvatarURL.IsValid() {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:87
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:88
				qw422016.N().S(` set a profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:89
			} else if prevContent.AvatarURL.IsValid() && !content.AvatarURL.IsValid() {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:89
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:90
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:90
				qw422016.N().S(` removed their profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:91
			} else if prevContent.AvatarURL != content.AvatarURL {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:91
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:92
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:92
				qw422016.N().S(` changed their profile picture.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:93
			}
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:93
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:94
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:94
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:95
			p.streamprettyPrintMember(qw422016, target)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:95
			qw422016.N().S(`joined the room.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:96
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:96
		qw422016.N().S(`
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:97
	case "leave":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:97
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:98
		if sender == target {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:98
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:99
			if prevContent.Membership == "invite" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:99
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:100
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:100
				qw422016.N().S(` rejected invite.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:101
			} else {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:101
				qw422016.N().S(`
                    `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:102
				p.streamprettyPrintMember(qw422016, target)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:102
				qw422016.N().S(` left the room.
                `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:103
			}
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:103
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:104
		} else if prevContent.Membership == "ban" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:104
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			p.streamprettyPrintMember(qw422016, sender)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			qw422016.N().S(` unbanned `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			p.streamprettyPrintMember(qw422016, target)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:105
			qw422016.N().S(`.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:106
		} else if prevContent.Membership == "leave" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:106
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			p.streamprettyPrintMember(qw422016, sender)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.N().S(` kicked `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			p.streamprettyPrintMember(qw422016, target)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:107
			qw422016.N().S(`.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:108
		} else if prevContent.Membership == "invite" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:108
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			p.streamprettyPrintMember(qw422016, sender)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.N().S(` withdrew `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			p.streamprettyPrintMember(qw422016, target)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:109
			qw422016.N().S(`'s invite.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:110
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:110
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			p.streamprettyPrintMember(qw422016, target)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:111
			qw422016.N().S(` left the room.
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:112
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:112
		qw422016.N().S(`
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:113
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:113
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
func (p *RoomChatPage) writetextForMRoomMemberEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	p.streamtextForMRoomMemberEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
func (p *RoomChatPage) textForMRoomMemberEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	p.writetextForMRoomMemberEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:114
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
func (p *RoomChatPage) streamtextForMRoomMessageEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:116
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:117
	switch ev.Content["msgtype"] {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:118
	case "m.image":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:118
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:120
		url := ev.Content["url"].(string)

		if thumbUrl, ok := ev.Content["thumbnail_url"].(string); ok {
			url = thumbUrl
		}

		mxc := mxclient.NewMXCURL(url, p.HomeserverBaseURL)

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:127
		qw422016.N().S(`
            <a href="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:128
		qw422016.E().S(mxc.ToURL())
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:128
		qw422016.N().S(`" rel="noopener">
                <img src="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:129
		qw422016.E().S(mxc.ToThumbURL(360, 360, "scale"))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:129
		qw422016.N().S(`" />
                <br>
                <sup>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:131
		qw422016.E().S(Str(ev.Content["body"]))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:131
		qw422016.N().S(`</sup>
            </a>
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:133
	case "m.file":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:133
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:134
		mxc := mxclient.NewMXCURL(Str(ev.Content["url"]), p.HomeserverBaseURL)

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:134
		qw422016.N().S(`
            <a href="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:135
		qw422016.E().S(mxc.ToURL())
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:135
		qw422016.N().S(`" rel="noopener">
                `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:136
		if ev.Content["thumbnail_url"] != "" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:136
			qw422016.N().S(`
                    <img src="`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:137
			qw422016.E().S(mxc.ToThumbURL(360, 360, "scale"))
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:137
			qw422016.N().S(`" />
                    <br>
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:139
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:139
		qw422016.N().S(`
                <sup>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:140
		qw422016.E().S(Str(ev.Content["body"]))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:140
		qw422016.N().S(`</sup>
            </a>
            m.file
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:143
	case "m.location":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:143
		qw422016.N().S(`
            m.location Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:145
	case "m.video":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:145
		qw422016.N().S(`
            m.video Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:147
	case "m.audio":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:147
		qw422016.N().S(`
            m.audio Event
        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:149
	default:
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:149
		qw422016.N().S(` `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:149
		qw422016.N().S(`
            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:151
		var formattedOk bool
		var sanitizedFormattedBody, body string

		if ev.Content["format"] == "org.matrix.custom.html" {
			if formattedBodyStr, ok := ev.Content["formatted_body"].(string); ok {
				sanitizedFormattedBody, formattedOk = p.Sanitizer.Sanitize(formattedBodyStr)
			}
		}
		if !formattedOk {
			if bodyStr, ok := ev.Content["body"].(string); ok {
				body = bodyStr
			}
		}

		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:164
		qw422016.N().S(`

            `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:166
		if formattedOk {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:166
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:167
			qw422016.N().S(sanitizedFormattedBody)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:167
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:168
		} else if body != "" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:168
			qw422016.N().S(`
                `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:169
			qw422016.E().S(body)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:169
			qw422016.N().S(`
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:170
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:170
			qw422016.N().S(`
                <span class="redacted">Redacted or Malformed Event</span>
            `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:172
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:172
		qw422016.N().S(`
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:173
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:173
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
func (p *RoomChatPage) writetextForMRoomMessageEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	p.streamtextForMRoomMessageEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
func (p *RoomChatPage) textForMRoomMessageEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	p.writetextForMRoomMessageEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:174
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
func streamprintStateChange(qw422016 *qt422016.Writer, ev gomatrix.Event, key, thing string) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:176
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:178
	prev := Str(ev.PrevContent[key])
	cur := Str(ev.Content[key])

	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:180
	qw422016.N().S(`

    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:182
	qw422016.E().S(ev.Sender)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:182
	qw422016.N().S(`

    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:184
	if cur != "" && prev == "" {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:184
		qw422016.N().S(`
        set the `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:185
		qw422016.E().S(thing)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:185
		qw422016.N().S(` to "`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:185
		qw422016.E().S(cur)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:185
		qw422016.N().S(`".
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:186
	} else if cur == "" && prev != "" {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:186
		qw422016.N().S(`
        removed the `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
		qw422016.E().S(thing)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
		qw422016.N().S(` "`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
		qw422016.E().S(prev)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:187
		qw422016.N().S(`".
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:188
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:188
		qw422016.N().S(`
        changed the `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.E().S(thing)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.N().S(` to "`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.E().S(cur)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.N().S(`" from "`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.E().S(prev)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:189
		qw422016.N().S(`".
    `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:190
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:190
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
func writeprintStateChange(qq422016 qtio422016.Writer, ev gomatrix.Event, key, thing string) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	streamprintStateChange(qw422016, ev, key, thing)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
func printStateChange(ev gomatrix.Event, key, thing string) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	writeprintStateChange(qb422016, ev, key, thing)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:191
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:193
func (p *RoomChatPage) streamprettyPrintMember(qw422016 *qt422016.Writer, mxid string) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:193
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:194
	memberInfo := p.MemberMap[mxid]

	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:194
	qw422016.N().S(`

    <a href="./room/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:196
	qw422016.E().S(p.RoomInfo.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:196
	qw422016.N().S(`/members/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:196
	qw422016.E().S(mxid)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:196
	qw422016.N().S(`">

        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:198
	if memberInfo.AvatarURL.IsValid() {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:198
		qw422016.N().S(`
            <img class="avatar userAvatar" src="`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:199
		qw422016.E().S(memberInfo.AvatarURL.ToThumbURL(48, 48, "crop"))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:199
		qw422016.N().S(`" />
        `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:200
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:200
		qw422016.N().S(`
            <img class="avatar userAvatar" src="./img/logo_missing.png" />
        `)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:202
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:202
	qw422016.N().S(`


        `)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:205
	qw422016.E().S(memberInfo.GetName())
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:205
	qw422016.N().S(`
    </a>
`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
func (p *RoomChatPage) writeprettyPrintMember(qq422016 qtio422016.Writer, mxid string) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	p.streamprettyPrintMember(qw422016, mxid)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
func (p *RoomChatPage) prettyPrintMember(mxid string) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	p.writeprettyPrintMember(qb422016, mxid)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:207
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
func (p *RoomChatPage) streamprintEvent(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:210
	qw422016.N().S(`<tr>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:212
	p.streamprintPermalinkColumn(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:213
	switch ev.Type {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:214
	case "m.room.message":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:215
		if ev.Content["msgtype"] == "m.emote" {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:215
			qw422016.N().S(`<td nowrap></td><td>*`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:218
			qw422016.N().S(` `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:218
			p.streamprettyPrintMember(qw422016, ev.Sender)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:219
			qw422016.N().S(` `)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:219
			p.streamtextForMRoomMessageEvent(qw422016, ev)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:219
			qw422016.N().S(`</td>`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:221
		} else {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:221
			qw422016.N().S(`<td nowrap>`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:223
			if ev.Content["msgtype"] == "m.emote" {
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:223
				qw422016.N().S(`*`)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:223
				qw422016.N().S(` `)
				//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:223
			}
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:224
			p.streamprettyPrintMember(qw422016, ev.Sender)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:224
			qw422016.N().S(`</td><td>`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
			p.streamtextForMRoomMessageEvent(qw422016, ev)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:226
			qw422016.N().S(`</td>`)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:227
		}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
	case "m.room.member":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:229
		qw422016.N().S(`<td nowrap></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
		p.streamtextForMRoomMemberEvent(qw422016, ev)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:231
		qw422016.N().S(`</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:232
	case "m.room.name":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:232
		qw422016.N().S(`<td nowrap></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:234
		streamprintStateChange(qw422016, ev, "name", "room name")
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:234
		qw422016.N().S(`</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
	case "m.room.topic":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:235
		qw422016.N().S(`<td nowrap></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:237
		streamprintStateChange(qw422016, ev, "topic", "room topic")
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:237
		qw422016.N().S(`</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:238
	case "m.room.avatar":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:238
		qw422016.N().S(`<td nowrap></td><td>Room Avatar Renderer.</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:243
	case "m.room.power_levels":
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:243
		qw422016.N().S(`<td nowrap></td><td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:245
		p.streamprettyPrintMember(qw422016, ev.Sender)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:245
		qw422016.N().S(`changed room power levels.</td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:246
	default:
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:246
		qw422016.N().S(`<td nowrap>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:247
		qw422016.E().S(ev.Type)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:247
		qw422016.N().S(`</td><td>Cannot Understand Event.</td>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:249
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:249
	qw422016.N().S(`</tr>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
func (p *RoomChatPage) writeprintEvent(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	p.streamprintEvent(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
func (p *RoomChatPage) printEvent(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	p.writeprintEvent(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:251
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:253
func (p *RoomChatPage) streamprintPermalinkColumn(qw422016 *qt422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:253
	qw422016.N().S(`<td class="timestamp" nowrap><a href="https://matrix.to/#/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	qw422016.E().S(p.RoomInfo.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	qw422016.N().S(`/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	qw422016.E().S(ev.ID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	qw422016.N().S(`">`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	streamprintTimestamp(qw422016, ev.Timestamp)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:255
	qw422016.N().S(`</a></td>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
func (p *RoomChatPage) writeprintPermalinkColumn(qq422016 qtio422016.Writer, ev gomatrix.Event) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	p.streamprintPermalinkColumn(qw422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
func (p *RoomChatPage) printPermalinkColumn(ev gomatrix.Event) string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	p.writeprintPermalinkColumn(qb422016, ev)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:257
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:261
func (p *RoomChatPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:261
	qw422016.N().S(`Public Room Timeline -`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:262
	qw422016.E().S(p.RoomInfo.Name)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:262
	qw422016.N().S(`- Riot Static`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
func (p *RoomChatPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
func (p *RoomChatPage) Title() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:263
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:265
func (p *RoomChatPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:266
	if !p.ReachedRoomCreate {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:266
		qw422016.N().S(`<link rel="next" href="?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:267
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:267
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:267
		qw422016.N().D(p.CurrentOffset + p.PageSize)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:267
		qw422016.N().S(`">`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:268
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:269
	if len(p.Events) > 0 {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:269
		qw422016.N().S(`<link rel="prev" href="?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
		qw422016.N().D(p.CurrentOffset - len(p.Events))
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:270
		qw422016.N().S(`">`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:271
	}
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
func (p *RoomChatPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
func (p *RoomChatPage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:272
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:274
func (p *RoomChatPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:275
	StreamPrintRoomHeader(qw422016, p.RoomInfo)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
func (p *RoomChatPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
func (p *RoomChatPage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:276
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:278
func (p *RoomChatPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:278
	qw422016.N().S(`<div class="paginate">`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:280
	if p.ReachedRoomCreate {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:280
		qw422016.N().S(`<h4>You have reached the beginning of time (for this room).</h4>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:282
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:282
		qw422016.N().S(`<a href="./room/`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.E().S(p.RoomInfo.RoomID)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.N().S(`/?anchor=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.E().S(p.Anchor)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.N().S(`&offset=`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.N().D(p.CurrentOffset + p.PageSize)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:283
		qw422016.N().S(`"><h4>Load older messages</h4></a>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:286
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:286
	qw422016.N().S(`</div><hr>`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:290
	if len(p.Events) > 0 {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:290
		qw422016.N().S(`<table id="timeline"><thead><tr><th>Timestamp</th><th>&nbsp;</th><th>Message</th></tr></thead><tbody>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:300
		for _, event := range p.Events {
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:301
			p.streamprintEvent(qw422016, event)
			//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:302
		}
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:302
		qw422016.N().S(`</tbody></table>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:305
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:305
		qw422016.N().S(`<h3>No Events</h3>`)
		//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:307
	}
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:307
	qw422016.N().S(`<hr><div class="paginate"><a href="./room/`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.E().S(p.RoomInfo.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.N().S(`/?anchor=`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.E().S(p.Anchor)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.N().S(`&offset=`)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.N().D(p.CurrentOffset - len(p.Events))
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:311
	qw422016.N().S(`"><h4>Show newer messages</h4></a></div><hr><a href="./">Back to Room List</a>`)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
func (p *RoomChatPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
}

//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
func (p *RoomChatPage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-chat.qtpl:318
}
