// This file is automatically generated by qtc from "room-memberinfo.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:1
package templates

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:1
import "github.com/t3chguy/riot-static/mxclient"

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:5
type RoomMemberInfoPage struct {
	RoomInfo   mxclient.RoomInfo
	MemberInfo mxclient.MemberInfo
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:12
func (p *RoomMemberInfoPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:12
	qw422016.N().S(`
    Public Room Servers - `)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:13
	qw422016.E().S(p.RoomInfo.Name)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:13
	qw422016.N().S(` - Riot Static
`)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
func (p *RoomMemberInfoPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
func (p *RoomMemberInfoPage) Title() string {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:14
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:16
func (p *RoomMemberInfoPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:16
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
func (p *RoomMemberInfoPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
func (p *RoomMemberInfoPage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:17
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:19
func (p *RoomMemberInfoPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:19
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:20
	StreamPrintRoomHeader(qw422016, p.RoomInfo)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:20
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
func (p *RoomMemberInfoPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
func (p *RoomMemberInfoPage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:21
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:24
func (p *RoomMemberInfoPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:24
	qw422016.N().S(`MemberInfo of`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:26
	qw422016.N().S(` `)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:26
	qw422016.E().S(p.MemberInfo.MXID)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:26
	qw422016.N().S(`<hr><table><tr><td>Avatar</td><td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:33
	if p.MemberInfo.AvatarURL.IsValid() {
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:33
		qw422016.N().S(`<a href="`)
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:34
		qw422016.E().S(p.MemberInfo.AvatarURL.ToURL())
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:34
		qw422016.N().S(`"><img src="`)
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:34
		qw422016.E().S(p.MemberInfo.AvatarURL.ToThumbURL(48, 48, "crop"))
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:34
		qw422016.N().S(`" /></a>`)
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:35
	} else {
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:35
		qw422016.N().S(`<img src="./img/logo_missing.png" />`)
		//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:37
	}
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:37
	qw422016.N().S(`</td></tr><tr><td>MXID</td><td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:42
	qw422016.E().S(p.MemberInfo.MXID)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:42
	qw422016.N().S(`</td></tr><tr><td>Display Name</td><td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:46
	qw422016.E().S(p.MemberInfo.DisplayName)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:46
	qw422016.N().S(`</td></tr><tr><td>Permalink</td><td><a href="https://matrix.to/#/`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:50
	qw422016.E().S(p.MemberInfo.MXID)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:50
	qw422016.N().S(`">https://matrix.to/#/`)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:50
	qw422016.E().S(p.MemberInfo.MXID)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:50
	qw422016.N().S(`</a></td></tr></table><a href="./">Back to Room List</a>`)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
func (p *RoomMemberInfoPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
}

//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
func (p *RoomMemberInfoPage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-memberinfo.qtpl:56
}
