// This file is automatically generated by qtc from "rooms.qtpl".
// See https://github.com/valyala/quicktemplate for details.

// Rooms (index) page template. Implements BasePage methods.
//

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:3
package templates

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:3
import "github.com/matrix-org/gomatrix"

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:6
type RoomsPage struct {
	// inherit from base page, so its' title is used in error page.
	BasePage

	Rooms    []gomatrix.PublicRoomsChunk
	PageSize int
	Page     int
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:17
func (p *RoomsPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:18
	StreamPaginatorHeadLinks(qw422016, p)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
func (p *RoomsPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
func (p *RoomsPage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:21
func (p *RoomsPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:21
	qw422016.N().S(`<h1>Riot-Static</h1>`)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
func (p *RoomsPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
func (p *RoomsPage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:23
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:25
func (p *RoomsPage) streamprintRoomRow(qw422016 *qt422016.Writer, Room gomatrix.PublicRoomsChunk) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:25
	qw422016.N().S(`<tr><td><a href="./room/`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:28
	qw422016.E().S(Room.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:28
	qw422016.N().S(`">`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:29
	if Room.AvatarUrl != "" {
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:29
		qw422016.N().S(`<img src="`)
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:30
		qw422016.E().S(Room.AvatarUrl)
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:30
		qw422016.N().S(`" />`)
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:31
	} else {
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:31
		qw422016.N().S(`<img src="./img/logo_missing.png" />`)
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:33
	}
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:33
	qw422016.N().S(`</a></td><td><a href="./room/`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:37
	qw422016.E().S(Room.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:37
	qw422016.N().S(`"><div>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:38
	StreamStrFallback(qw422016, Room.Name, Room.CanonicalAlias, Room.RoomID)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:38
	qw422016.N().S(`</div><sup>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:39
	qw422016.E().S(Room.CanonicalAlias)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:39
	qw422016.N().S(`</sup></a></td><td>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:42
	qw422016.N().D(Room.NumJoinedMembers)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:42
	qw422016.N().S(`</td><td>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:43
	qw422016.E().S(Room.Topic)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:43
	qw422016.N().S(`</td></tr>`)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
func (p *RoomsPage) writeprintRoomRow(qq422016 qtio422016.Writer, Room gomatrix.PublicRoomsChunk) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	p.streamprintRoomRow(qw422016, Room)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
func (p *RoomsPage) printRoomRow(Room gomatrix.PublicRoomsChunk) string {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	p.writeprintRoomRow(qb422016, Room)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:45
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:47
func (p *RoomsPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:49
	StreamPaginatorCurPage(qw422016, p)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:49
	qw422016.N().S(`<table id="roomList"><thead><tr><th>Logo</th><th>Name & Alias</th><th>#Members</th><th>Topic</th></tr></thead><tbody>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:61
	for _, Room := range p.Rooms {
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:62
		p.streamprintRoomRow(qw422016, Room)
		//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:63
	}
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:63
	qw422016.N().S(`</tbody></table>`)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:67
	StreamPaginatorFooter(qw422016, p)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
func (p *RoomsPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
func (p *RoomsPage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:69
}

//line src\github.com\t3chguy\riot-static\templates\rooms.qtpl:74
func (p *RoomsPage) CurPage() int {
	return p.Page
}
func (p *RoomsPage) HasNextPage() bool {
	return len(p.Rooms) == p.PageSize
}
func (p *RoomsPage) BaseUrl() string {
	return "./"
}
