// This file is automatically generated by qtc from "room-servers.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:1
package templates

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:1
import "github.com/t3chguy/riot-static/mxclient"

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:5
type RoomServersPage struct {
	RoomInfo mxclient.RoomInfo
	Servers  mxclient.StringIntPairList
	PageSize int
	Page     int
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:14
func (p *RoomServersPage) streamprintServer(qw422016 *qt422016.Writer, server mxclient.StringIntPair) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:14
	qw422016.N().S(`
    <tr>
        <td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:16
	qw422016.E().S(server.Key)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:16
	qw422016.N().S(`</td>
        <td>`)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:17
	qw422016.N().D(server.Value)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:17
	qw422016.N().S(`</td>
    </tr>
`)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
func (p *RoomServersPage) writeprintServer(qq422016 qtio422016.Writer, server mxclient.StringIntPair) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	p.streamprintServer(qw422016, server)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
func (p *RoomServersPage) printServer(server mxclient.StringIntPair) string {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	p.writeprintServer(qb422016, server)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:19
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:23
func (p *RoomServersPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:23
	qw422016.N().S(`
    Public Room Servers - `)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:24
	qw422016.E().S(p.RoomInfo.Name)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:24
	qw422016.N().S(` - Riot Static
`)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
func (p *RoomServersPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	p.StreamTitle(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
func (p *RoomServersPage) Title() string {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	p.WriteTitle(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:25
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:27
func (p *RoomServersPage) StreamHead(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:27
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
func (p *RoomServersPage) WriteHead(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	p.StreamHead(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
func (p *RoomServersPage) Head() string {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	p.WriteHead(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:28
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:30
func (p *RoomServersPage) StreamHeader(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:30
	qw422016.N().S(`
    `)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:31
	StreamPrintRoomHeader(qw422016, p.RoomInfo)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:31
	qw422016.N().S(`
`)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
func (p *RoomServersPage) WriteHeader(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	p.StreamHeader(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
func (p *RoomServersPage) Header() string {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	p.WriteHeader(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:32
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:35
func (p *RoomServersPage) StreamBody(qw422016 *qt422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:37
	StreamPaginatorCurPage(qw422016, p)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:37
	qw422016.N().S(`<table><thead><tr><th>Server</th><th>Number of Users in this Room</th></tr></thead><tbody>`)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:47
	for _, server := range p.Servers {
		//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:48
		p.streamprintServer(qw422016, server)
		//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:49
	}
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:49
	qw422016.N().S(`</tbody></table>`)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:53
	StreamPaginatorFooter(qw422016, p)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
func (p *RoomServersPage) WriteBody(qq422016 qtio422016.Writer) {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	p.StreamBody(qw422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
func (p *RoomServersPage) Body() string {
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	p.WriteBody(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	qs422016 := string(qb422016.B)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
	//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
	return qs422016
//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:55
}

//line src\github.com\t3chguy\riot-static\templates\room-servers.qtpl:62
func (p *RoomServersPage) CurPage() int {
	return p.Page
}
func (p *RoomServersPage) HasNextPage() bool {
	return len(p.Servers) == p.PageSize
}
func (p *RoomServersPage) BaseUrl() string {
	return RoomBaseUrl(p.RoomInfo.RoomID) + "/servers/"
}
